version: '3.9'

services:
  client-processing-db:
    image: postgres:15
    container_name: pg_client_processing
    environment:
      POSTGRES_USER: client
      POSTGRES_PASSWORD: clientpass
      POSTGRES_DB: clientdb
    ports:
      - "5432:5432"
    volumes:
      - client_pgdata:/var/lib/postgresql/data

  card-processing-db:
    image: postgres:15
    container_name: pg_account_processing
    environment:
      POSTGRES_USER: account
      POSTGRES_PASSWORD: accountpass
      POSTGRES_DB: accountdb
    ports:
      - "5433:5432"
    volumes:
      - account_pgdata:/var/lib/postgresql/data

  payment-processing-db:
    image: postgres:15
    container_name: pg_credit_processing
    environment:
      POSTGRES_USER: credit
      POSTGRES_PASSWORD: creditpass
      POSTGRES_DB: creditdb
    ports:
      - "5434:5432"
    volumes:
      - credit_pgdata:/var/lib/postgresql/data

volumes:
  client_pgdata:
  account_pgdata:
  credit_pgdata:
