version: '3.9'

services:
  client-processing-db:
    image: postgres:15
    container_name: pg_client_processing
    environment:
      POSTGRES_USER: client
      POSTGRES_PASSWORD: clientpass
      POSTGRES_DB: clientdb
    ports:
      - "5432:5432"
    volumes:
      - client_pgdata:/var/lib/postgresql/data

  card-processing-db:
    image: postgres:15
    container_name: pg_account_processing
    environment:
      POSTGRES_USER: account
      POSTGRES_PASSWORD: accountpass
      POSTGRES_DB: accountdb
    ports:
      - "5433:5432"
    volumes:
      - account_pgdata:/var/lib/postgresql/data

  payment-processing-db:
    image: postgres:15
    container_name: pg_credit_processing
    environment:
      POSTGRES_USER: credit
      POSTGRES_PASSWORD: creditpass
      POSTGRES_DB: creditdb
    ports:
      - "5434:5432"
    volumes:
      - credit_pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  client_pgdata:
  account_pgdata:
  credit_pgdata:
