server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/accountdb
    username: account
    password: accountpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
