server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/accountdb
    username: account
    password: accountpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/client/db.changelog-master.xml

kafka-topics:
  client-products: client_products
  client-credit-products: client_credit_products
  client-transactions: client-transactions
  client-cards: client-cards

t1:
  kafka:
    session:
      timeout:
        ms: 45000
    max:
      partition:
        fetch:
          bytes: 300000
      poll:
        records: 1
        interval:
          ms: 300000
    consumer:
      heartbeat:
        interval: 3000


logging:
  level:
    org.springframework.kafka: DEBUG
    org.springframework.kafka.listener: DEBUG
    org.springframework.kafka.support.serializer.JsonDeserializer: DEBUG
    org.apache.kafka: DEBUG
    com.bankx: DEBUG