server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/creditdb
    username: credit
    password: creditpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

kafka-topics:
  client-credit-products: client_credit_products

t1:
  kafka:
    session:
      timeout:
        ms: 45000
    max:
      partition:
        fetch:
          bytes: 300000
      poll:
        records: 1
        interval:
          ms: 300000
    consumer:
      heartbeat:
        interval: 3000