server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/creditdb
    username: credit
    password: creditpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
